/**
 * Full Listing Export — generates a downloadable ZIP containing:
 * - Upscaled product images (4x, eBay optimized)
 * - Store banner (1200×200)
 * - eBay listing as HTML (ready to paste)
 * - Listing data as JSON
 * - Keywords CSV
 * - README.txt with instructions
 */

import { Router } from "express";
import multer from "multer";
import JSZip from "jszip";
import sharp from "sharp";
import { callAIJSON } from "../ai/models.js";
import { buildListingPrompt, SYSTEM_PROMPTS, type ProductData } from "../ai/prompts.js";
import { scrapeUrl, extractKeywordsFromText } from "../scraper/index.js";
import { generateSEOReport } from "../ebay/seo.js";
import { trackUsage } from "../db/index.js";

const router = Router();

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 50 * 1024 * 1024, files: 20 },
});

interface ListingExportData {
  title: string;
  subtitle?: string;
  category: string;
  condition: string;
  price: number;
  description: string;
  itemSpecifics: Record<string, string>;
  keywords: string[];
  tags?: string[];
  shippingRecommendation?: string;
  seoScore?: number;
  cassiniTips?: string[];
}

function buildEbayHTML(listing: ListingExportData, storeName = "My eBay Store"): string {
  const specificsRows = Object.entries(listing.itemSpecifics ?? {})
    .filter(([, v]) => v && v !== "N/A")
    .map(([k, v]) => `<tr><td style="font-weight:bold;padding:6px 12px;background:#f8f8f8;border:1px solid #ddd;width:40%">${k}</td><td style="padding:6px 12px;border:1px solid #ddd">${v}</td></tr>`)
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${listing.title}</title>
<style>
  body{font-family:Arial,Helvetica,sans-serif;color:#222;max-width:800px;margin:0 auto;padding:20px;background:#fff}
  h1{color:#0064d2;font-size:22px;border-bottom:2px solid #0064d2;padding-bottom:10px}
  h2{color:#333;font-size:16px;margin-top:24px}
  .badge{display:inline-block;background:#0064d2;color:#fff;padding:4px 10px;border-radius:4px;font-size:12px;margin-bottom:12px}
  .specs-table{width:100%;border-collapse:collapse;margin:12px 0}
  .keywords{display:flex;flex-wrap:wrap;gap:6px;margin:12px 0}
  .keyword{background:#f0f7ff;border:1px solid #c0d8f0;padding:4px 10px;border-radius:20px;font-size:12px;color:#0064d2}
  .tips{background:#fffbeb;border-left:4px solid #f59e0b;padding:12px 16px;margin:12px 0}
  .tips li{margin:4px 0;font-size:13px}
  .footer{margin-top:30px;padding-top:12px;border-top:1px solid #eee;font-size:11px;color:#999;text-align:center}
  ul.features{padding-left:20px}
  ul.features li{margin:6px 0;font-size:14px}
</style>
</head>
<body>
<span class="badge">eBay Listing — Generated by Pixlance AI</span>
<h1>${listing.title}</h1>

${listing.subtitle ? `<p style="color:#666;font-size:14px;margin-top:-8px"><em>${listing.subtitle}</em></p>` : ""}

<table style="margin:12px 0">
  <tr><td style="color:#666;padding-right:16px">Category</td><td><strong>${listing.category}</strong></td></tr>
  <tr><td style="color:#666;padding-right:16px">Condition</td><td><strong>${listing.condition}</strong></td></tr>
  <tr><td style="color:#666;padding-right:16px">Suggested Price</td><td><strong style="color:#0064d2;font-size:18px">£${listing.price}</strong></td></tr>
  ${listing.shippingRecommendation ? `<tr><td style="color:#666;padding-right:16px">Shipping</td><td>${listing.shippingRecommendation}</td></tr>` : ""}
</table>

<h2>Description</h2>
${listing.description}

<h2>Item Specifics</h2>
<table class="specs-table">${specificsRows}</table>

<h2>SEO Keywords</h2>
<div class="keywords">
  ${(listing.keywords ?? []).map(k => `<span class="keyword">${k}</span>`).join("")}
</div>

${listing.cassiniTips?.length ? `
<h2>Cassini Optimization Tips</h2>
<div class="tips"><ul>${listing.cassiniTips.map(t => `<li>${t}</li>`).join("")}</ul></div>
` : ""}

<div class="footer">Generated by Pixlance AI eBay Seller Suite &bull; ${new Date().toLocaleDateString("en-GB")} &bull; Store: ${storeName}</div>
</body>
</html>`;
}

function buildReadme(listing: ListingExportData, imageCount: number): string {
  return `PIXLANCE AI LISTING EXPORT
Generated: ${new Date().toLocaleString("en-GB")}
==========================================

PRODUCT: ${listing.title}
CATEGORY: ${listing.category}
PRICE: £${listing.price}
SEO SCORE: ${listing.seoScore ?? "N/A"}/100

FILES IN THIS PACKAGE:
- listing.html     → Paste this into eBay's HTML editor (Advanced listing)
- listing.json     → Full listing data in JSON format
- keywords.csv     → SEO keywords — use in eBay search tags
- images/          → ${imageCount} product image(s), upscaled 4x for maximum eBay quality
- banner.jpg       → eBay store banner (1200×200px)
- README.txt       → This file

HOW TO LIST ON EBAY:
1. Go to eBay → Sell → Create listing
2. Paste title: ${listing.title}
3. Select category: ${listing.category}
4. Set condition: ${listing.condition}
5. Set price: £${listing.price}
6. Upload images from the /images folder (main image first)
7. In description, click HTML editor → paste contents of listing.html
8. Fill item specifics from listing.json
9. Save and publish!

CASSINI SEO TIPS:
${(listing.cassiniTips ?? []).map((t, i) => `${i + 1}. ${t}`).join("\n")}

KEYWORDS TO USE IN TAGS:
${(listing.keywords ?? []).join(", ")}

---
Generated by Pixlance AI — https://pixlance.pages.dev
`;
}

// ─── Export from URL (scrape + generate + package ZIP) ──────────────────────
router.post("/export/from-url", async (req, res) => {
  const { url, marketplace = "eBay UK", storeName = "My eBay Store", bannerTagline = "Quality Products, Fast Shipping" } = req.body as {
    url: string;
    marketplace?: string;
    storeName?: string;
    bannerTagline?: string;
  };

  if (!url) { res.status(400).json({ error: "URL required" }); return; }

  try {
    // Step 1: Scrape product data
    const scraped = await scrapeUrl(url);
    const rawText = [scraped.title, scraped.description, ...Object.values(scraped.specs ?? {})].join(" ");
    const extractedKeywords = extractKeywordsFromText(rawText);

    const product: ProductData = {
      title: scraped.title,
      description: scraped.description,
      brand: scraped.brand,
      price: scraped.price,
      specs: scraped.specs,
      keywords: extractedKeywords.slice(0, 10),
      sourceUrl: url,
    };

    // Step 2: Generate listing
    const prompt = buildListingPrompt(product, { marketplace });
    const listing = await callAIJSON<ListingExportData>(prompt, "listing", SYSTEM_PROMPTS.listing);

    // Step 3: Process images (download + upscale to 4x)
    const zip = new JSZip();
    const imagesFolder = zip.folder("images")!;
    let processedImageCount = 0;

    const imageUrls = (scraped.images ?? []).slice(0, 12).filter(Boolean);
    await Promise.allSettled(
      imageUrls.map(async (imgUrl, i) => {
        try {
          const imgRes = await fetch(imgUrl, {
            headers: { "User-Agent": "Mozilla/5.0 (compatible; Pixlance/1.0)" },
            signal: AbortSignal.timeout(10000),
          });
          if (!imgRes.ok) return;
          const imgBuffer = Buffer.from(await imgRes.arrayBuffer());

          // Upscale 4x with sharp
          const meta = await sharp(imgBuffer).metadata();
          const targetW = Math.min((meta.width ?? 400) * 4, 3200);
          const targetH = Math.min((meta.height ?? 400) * 4, 3200);

          const upscaled = await sharp(imgBuffer)
            .resize(targetW, targetH, { kernel: sharp.kernel.lanczos3, fit: "fill" })
            .sharpen(1.2, 1, 0.5)
            .jpeg({ quality: 95, chromaSubsampling: "4:4:4" })
            .toBuffer();

          imagesFolder.file(`image_${i + 1}_${targetW}x${targetH}.jpg`, upscaled);
          processedImageCount++;
        } catch { /* skip failed images */ }
      })
    );

    // Step 4: Generate store banner (1200×200)
    const bannerSvg = `<svg width="1200" height="200" xmlns="http://www.w3.org/2000/svg">
      <defs><linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" style="stop-color:#0f172a"/><stop offset="100%" style="stop-color:#1e3a5f33"/>
      </linearGradient></defs>
      <rect width="1200" height="200" fill="url(#bg)"/>
      <rect x="0" y="196" width="1200" height="4" fill="#3b82f6"/>
      <text x="600" y="84" font-family="Arial,sans-serif" font-size="56" font-weight="bold" fill="#fff" text-anchor="middle" dominant-baseline="middle">${storeName.replace(/[<>&]/g, "")}</text>
      <text x="600" y="144" font-family="Arial,sans-serif" font-size="28" fill="#3b82f6" text-anchor="middle" dominant-baseline="middle">${bannerTagline.replace(/[<>&]/g, "")}</text>
    </svg>`;
    const bannerBuffer = await sharp(Buffer.from(bannerSvg)).resize(1200, 200).jpeg({ quality: 95 }).toBuffer();
    zip.file("banner.jpg", bannerBuffer);

    // Step 5: Build HTML listing
    const html = buildEbayHTML(listing, storeName);
    zip.file("listing.html", html);

    // Step 6: JSON export
    const seoReport = generateSEOReport({
      title: listing.title ?? "",
      description: listing.description ?? "",
      itemSpecifics: listing.itemSpecifics ?? {},
      price: listing.price,
      category: listing.category,
    });
    zip.file("listing.json", JSON.stringify({ listing, seoReport, scraped: { title: scraped.title, sourceDomain: scraped.sourceDomain, scrapedAt: scraped.scrapedAt } }, null, 2));

    // Step 7: Keywords CSV
    const kwCsv = ["Keyword,Type\n",
      ...(listing.keywords ?? []).map(k => `"${k}",primary\n`),
      ...(listing.tags ?? []).map(t => `"${t}",tag\n`),
    ].join("");
    zip.file("keywords.csv", kwCsv);

    // Step 8: README
    zip.file("README.txt", buildReadme(listing, processedImageCount));

    // Generate ZIP
    const zipBuffer = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE", compressionOptions: { level: 6 } });

    const safeName = (listing.title ?? "listing").slice(0, 40).replace(/[^a-z0-9]/gi, "_").toLowerCase();
    res.set({
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="pixlance_${safeName}.zip"`,
      "Content-Length": zipBuffer.length.toString(),
    });
    res.send(zipBuffer);

    // Track usage async
    void trackUsage("listing_exported_url", undefined, req.ip ?? undefined, { url: url.slice(0, 100), imageCount: processedImageCount });
  } catch (err) {
    res.status(500).json({ error: String(err) });
  }
});

// ─── Export from uploaded images + optional keyword ─────────────────────────
router.post("/export/from-images", upload.array("images", 20), async (req, res) => {
  const files = req.files as Express.Multer.File[];
  const { keyword, marketplace = "eBay UK", storeName = "My eBay Store", bannerTagline = "Quality Products, Fast Shipping" } = req.body as {
    keyword?: string;
    marketplace?: string;
    storeName?: string;
    bannerTagline?: string;
  };

  if (!files?.length) { res.status(400).json({ error: "At least one image required" }); return; }

  try {
    const productTitle = keyword || files[0].originalname.replace(/\.[^.]+$/, "").replace(/[-_]/g, " ");

    // Generate listing from keyword/filename
    const product: ProductData = {
      title: productTitle,
      keywords: productTitle.toLowerCase().split(/\s+/).filter(Boolean),
    };
    const prompt = buildListingPrompt(product, { marketplace });
    const listing = await callAIJSON<ListingExportData>(prompt, "listing", SYSTEM_PROMPTS.listing);

    const zip = new JSZip();
    const imagesFolder = zip.folder("images")!;
    let processedImageCount = 0;

    // Upscale all uploaded images
    await Promise.allSettled(
      files.map(async (file, i) => {
        try {
          const meta = await sharp(file.buffer).metadata();
          const targetW = Math.min((meta.width ?? 400) * 4, 3200);
          const targetH = Math.min((meta.height ?? 400) * 4, 3200);

          const upscaled = await sharp(file.buffer)
            .resize(targetW, targetH, { kernel: sharp.kernel.lanczos3, fit: "fill" })
            .sharpen(1.2, 1, 0.5)
            .jpeg({ quality: 95, chromaSubsampling: "4:4:4" })
            .toBuffer();

          const name = `image_${i + 1}_${targetW}x${targetH}.jpg`;
          imagesFolder.file(name, upscaled);
          processedImageCount++;
        } catch { /* skip */ }
      })
    );

    // Banner
    const bannerSvg = `<svg width="1200" height="200" xmlns="http://www.w3.org/2000/svg">
      <defs><linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" style="stop-color:#0f172a"/><stop offset="100%" style="stop-color:#1e3a5f33"/>
      </linearGradient></defs>
      <rect width="1200" height="200" fill="url(#bg)"/>
      <rect x="0" y="196" width="1200" height="4" fill="#3b82f6"/>
      <text x="600" y="84" font-family="Arial,sans-serif" font-size="56" font-weight="bold" fill="#fff" text-anchor="middle" dominant-baseline="middle">${storeName.replace(/[<>&]/g, "")}</text>
      <text x="600" y="144" font-family="Arial,sans-serif" font-size="28" fill="#3b82f6" text-anchor="middle" dominant-baseline="middle">${bannerTagline.replace(/[<>&]/g, "")}</text>
    </svg>`;
    const bannerBuffer = await sharp(Buffer.from(bannerSvg)).resize(1200, 200).jpeg({ quality: 95 }).toBuffer();
    zip.file("banner.jpg", bannerBuffer);

    zip.file("listing.html", buildEbayHTML(listing, storeName));

    const seoReport = generateSEOReport({
      title: listing.title ?? "",
      description: listing.description ?? "",
      itemSpecifics: listing.itemSpecifics ?? {},
      price: listing.price,
      category: listing.category,
    });
    zip.file("listing.json", JSON.stringify({ listing, seoReport }, null, 2));

    const kwCsv = ["Keyword,Type\n", ...(listing.keywords ?? []).map(k => `"${k}",primary\n`)].join("");
    zip.file("keywords.csv", kwCsv);
    zip.file("README.txt", buildReadme(listing, processedImageCount));

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE", compressionOptions: { level: 6 } });
    const safeName = (listing.title ?? productTitle).slice(0, 40).replace(/[^a-z0-9]/gi, "_").toLowerCase();

    res.set({
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="pixlance_${safeName}.zip"`,
      "Content-Length": zipBuffer.length.toString(),
    });
    res.send(zipBuffer);

    void trackUsage("listing_exported_images", undefined, req.ip ?? undefined, { imageCount: processedImageCount });
  } catch (err) {
    res.status(500).json({ error: String(err) });
  }
});

// ─── Export from existing listing data ───────────────────────────────────────
router.post("/export/from-listing", async (req, res) => {
  const { listing, storeName = "My eBay Store", bannerTagline = "Quality Products, Fast Shipping", colorScheme = "blue" } = req.body as {
    listing: ListingExportData;
    storeName?: string;
    bannerTagline?: string;
    colorScheme?: string;
  };

  if (!listing) { res.status(400).json({ error: "listing data required" }); return; }

  try {
    const zip = new JSZip();

    const schemes: Record<string, { bg: string; accent: string }> = {
      blue:   { bg: "#0f172a", accent: "#3b82f6" },
      green:  { bg: "#0f2018", accent: "#22c55e" },
      purple: { bg: "#150f2a", accent: "#a855f7" },
      red:    { bg: "#2a0f0f", accent: "#ef4444" },
      gold:   { bg: "#1a1200", accent: "#f59e0b" },
    };
    const s = schemes[colorScheme] ?? schemes.blue;

    const bannerSvg = `<svg width="1200" height="200" xmlns="http://www.w3.org/2000/svg">
      <defs><linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" style="stop-color:${s.bg}"/><stop offset="100%" style="stop-color:${s.accent}33"/>
      </linearGradient></defs>
      <rect width="1200" height="200" fill="url(#bg)"/>
      <rect x="0" y="196" width="1200" height="4" fill="${s.accent}"/>
      <text x="600" y="84" font-family="Arial,sans-serif" font-size="56" font-weight="bold" fill="#fff" text-anchor="middle" dominant-baseline="middle">${storeName.replace(/[<>&]/g, "")}</text>
      <text x="600" y="144" font-family="Arial,sans-serif" font-size="28" fill="${s.accent}" text-anchor="middle" dominant-baseline="middle">${bannerTagline.replace(/[<>&]/g, "")}</text>
    </svg>`;
    const bannerBuffer = await sharp(Buffer.from(bannerSvg)).resize(1200, 200).jpeg({ quality: 95 }).toBuffer();
    zip.file("banner.jpg", bannerBuffer);
    zip.file("listing.html", buildEbayHTML(listing, storeName));
    zip.file("listing.json", JSON.stringify({ listing }, null, 2));

    const kwCsv = ["Keyword,Type\n", ...(listing.keywords ?? []).map(k => `"${k}",primary\n`), ...(listing.tags ?? []).map(t => `"${t}",tag\n`)].join("");
    zip.file("keywords.csv", kwCsv);
    zip.file("README.txt", buildReadme(listing, 0));

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE", compressionOptions: { level: 6 } });
    const safeName = (listing.title ?? "listing").slice(0, 40).replace(/[^a-z0-9]/gi, "_").toLowerCase();

    res.set({
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="pixlance_${safeName}.zip"`,
      "Content-Length": zipBuffer.length.toString(),
    });
    res.send(zipBuffer);

    void trackUsage("listing_exported", undefined, req.ip ?? undefined);
  } catch (err) {
    res.status(500).json({ error: String(err) });
  }
});

export default router;
